version: '3.4'

services:
  todoapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5050:80"
      - "44376:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - mssqldb
    networks:
      - todo-network

  mssqldb:
    ports:
        - "1433:1433"
    environment:
       SA_PASSWORD: "<Pass123>"
       ACCEPT_EULA: "Y"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql
    networks:
      - todo-network

volumes:
  mssql-server-linux-data:

networks:
  todo-network: